#!/bin/bash
# TrueCar script

# Remove current input and output files
hadoop fs -rm -r /user/cloudera/truecar/input;
hadoop fs -rm -r /user/cloudera/truecar/output;

# Put input file
hadoop fs -put map_reduce_input_data1.csv /user/cloudera/truecar/input;

# Compile, package, and create a JAR 
mkdir -p build;
javac -cp /usr/lib/hadoop/*:/usr/lib/hadoop-mapreduce/* TrueCar.java -d build -Xlint;
jar -cvf truecar.jar -C build/ .;

# Run TrueCar application 
hadoop jar truecar.jar org.myorg.TrueCar /user/cloudera/truecar/input /user/cloudera/truecar/output;

# Put output in local, clear first
rm -rf output;
mkdir output;
hadoop dfs -get /user/cloudera/truecar/output/* output;
echo "Day,ab_test_campaign,ab_test_variant,page_views" >> output/map_reduce_output_data.csv;
cat output/part-r-00000 >> output/map_reduce_output_data.csv;
cat output/map_reduce_output_data.csv;
